#!/bin/bash
estado=$(synclient -l | grep Touch)
if [[ $estado == '    TouchpadOff             = 0' ]];then
synclient TouchpadOff=1
notify-send bloqueado \touchpad -i /usr/share/pixmaps/gnome-mouse.png

else
synclient TouchpadOff=0
notify-send desbloqueado \touchpad -i /usr/share/pixmaps/gnome-mouse.png
fi
exit
