schema_version = 1
default_profile = "personal"

[profiles.personal]
default_provider = "gh"

[profiles.work]
default_provider = "gh"

[identity]
git_name = ""
git_email = ""
op_vault = ""
primary_machine = false

[providers]
enabled = ["gh", "gl"]

[git]
signing_enabled = true
commit_gpgsign = true
tag_gpgsign = true

[cli]
glab_config_dir = ""

[optional_integrations]
homebrew_core = true
homebrew_dev = true
homebrew_apps = true
homebrew_extras = false
homebrew_work = false
zinit = true
asdf = true
ssh_key_export = true
onepassword = true
