#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)
#export GNOME_DESKTOP_SESSION_ID="01" 
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi
export DE=gnome
# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice
if [[ $1 == "obox" ]]
	then
		exec ck-launch-session dbus-launch openbox-session
elif [[ $1 == "compiz" ]]
	then
		exec ck-launch-session dbus-launch compiz.sh
elif [[ $1 == pekwm ]]
	then
		exec ck-launch-session dbus-launch pekwm
elif [[ $1 == gnome ]]
	then
		exec ck-launch-session dbus-launch gnome-session
elif [[ $1 == awm ]]
	then
		exec ck-launch-session dbus-launch awesome
else
  echo "Choose a window manager"
fi
